name: chatdb
description: A AI application inspired from ChatGPT that communicates with databases
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.0
  shared_preferences:  ^2.5.3
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  http: ^1.5.0
  flutter_glow: ^0.3.2
  animations: ^2.0.11
  font_awesome_flutter: ^10.10.0
  line_icons: ^2.0.3
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  google_sign_in: ^7.1.1
  sqflite: ^2.4.2
  path: ^1.9.1
  excel: ^4.0.6
  file_picker: ^10.3.2
  excel_to_json: ^1.5.1
  cloud_firestore: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/icon1.svg
    - images/icon2.jpg
    - images/icon3.svg
    - images/icon4.svg
  fonts:
    - family: Gabriola
      fonts:
        - asset: fonts/Gabriola.ttf
    - family: LucidaSans
      fonts:
        - asset: fonts/LucidaSans.ttf
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Medium.ttf
    - family: DaysOne
      fonts:
        - asset: fonts/DaysOne-Regular.ttf


